### ISSUE TITLE
Syntax error in ex11.py

### ISSUE THREAD

**Issue by nehaldattani** [Iminevitable1/Python-Programming#1]
When i try to run this, it throws syntax error, please fix it.
<img width="959" alt="Ex_11_error" src="https://user-images.githubusercontent.com/1366458/83358568-02333e00-a3a7-11ea-8d15-26b7636b1e06.png">

**Comment by nehaldattani** [comment]
Here's the error in python 3
<img width="956" alt="Ex_11_error_p3" src="https://user-images.githubusercontent.com/1366458/83358624-6b1ab600-a3a7-11ea-8407-12557b6129aa.png">

**Comment by Iminevitable1** [comment]
By running it in Python version 3.8, The code runs perfectly.
